app:
  name: "Student Helper"

llm:
  ONLINE_OPENAI_GPT3:
    LOCAL_MODEL: False
    MODEL_PROVIDER: "OpenAI"
    MODEL_NAME: "gpt-3.5-turbo-0125"  # "gpt-3.5-turbo-0125", "gpt-3.5-turbo-instruct", "llama3:8b"
    TEMPERATURE: 0
    KEY: !ENV ${OPENAI_API_KEY}

  LOCAL_OLLAMA_LLAMA3:
    MODEL_PROVIDER: "Ollama"
    MODEL_NAME: "llama3:8b"

  LOCAL_DOCKER_OLLAMA_LLAMA3:
    LOCAL_MODEL: True
    MODEL_PROVIDER: "Ollama"
    MODEL_NAME: "llama3:8b"
    OLLAMA_HOST: "ollama"
    OLLAMA_PORT: 11434
