services:
  student_helper_backend:
    build:
      context: .
    container_name: student_helper_server
    networks:
      - student-helper-net
    volumes:
      - ./app1_data:/app/data
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - student-helper-net
    volumes:
      - /ollama:/root/.ollama


  # Use for Transcriber in later stage
  #faster-whisper-server-cpu:
  #  image: fedirz/faster-whisper-server:latest-cpu
  #  volumes:
  #    - ~/.cache/huggingface:/root/.cache/huggingface
  #  restart: unless-stopped
  #  ports:
  #    - "8000:8000"
  #  networks:
  #    - student-helper-net
  #  develop:
  #    watch:
  #      - path: faster_whisper_server
  #        action: rebuild


networks:
  student-helper-net:
    driver: bridge