services:
  student_helper_backend:
    build:
      context: .
    container_name: firstapp
    networks:
      - student-helper-net
    volumes:
      - ./app1_data:/app/data
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
      - OLLAMA_PORT=${OLLAMA_PORT}
      - MODEL_NAME=${MODEL_NAME}

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    networks:
      - student-helper-net
    volumes:
      - /ollama:/root/.ollama
    expose:
      - "11434"

  faster-whisper-server-cpu:
    image: fedirz/faster-whisper-server:latest-cpu
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - student-helper-net
    develop:
      watch:
        - path: faster_whisper_server
          action: rebuild


networks:
  student-helper-net:
    driver: bridge