services:
  student_helper_backend:
    build:
      context: .
    container_name: firstapp
    networks:
      - student-helper-net
    volumes:
      - ./app1_data:/app/data
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
      - OLLAMA_PORT=${OLLAMA_PORT}
      - MODEL_NAME=${MODEL_NAME}

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    networks:
      - student-helper-net
    volumes:
      - /ollama:/root/.ollama
    expose:
      - "11434"

networks:
  student-helper-net:
    driver: bridge