services:
  student_helper_backend:
    #image: firstapp:latest
    build:
      context: .
    container_name: firstapp
    ports:
      - "8080:80"
    volumes:
      - ./app1_data:/app/data
    environment:
      - .env

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - /ollama:/root/.ollama
    container_name: ollama
