app:
  name: "Student Helper"

llm_parser: # "schema" , "model"
  COMPREHENSION: "model"
  LANGUAGE_PRODUCTION: "model"

evaluator:
  ONLINE_OPENAI_GPT3:
    LOCAL_MODEL: False
    MODEL_PROVIDER: "OpenAI"
    MODEL_NAME: "gpt-3.5-turbo-0125"  # "gpt-3.5-turbo-0125", "gpt-3.5-turbo-instruct"
    TEMPERATURE: 0

  LOCAL_OLLAMA_LLAMA3:
    MODEL_PROVIDER: "Ollama"
    MODEL_NAME: "llama3:8b"

  LOCAL_DOCKER_OLLAMA_LLAMA3:
    LOCAL_MODEL: True
    MODEL_PROVIDER: "Ollama"
    MODEL_NAME: "llama3:8b"
    OLLAMA_HOST: "ollama"
    OLLAMA_PORT: 11434

transcriber:
  ONLINE_OPENAI_WHISPER:
    MODEL_PROVIDER: "OpenAI"
    MODEL_NAME: "whisper-1"
    LANGUAGE: "af"
    RESPONSE_FORMAT: "json"
    TEMPERATURE: 0

  OFFLINE_OPENAI_WHISPER:
    MODEL_NAME: "Systran/faster-distil-whisper-large-v3"
    DUMMY_API_KEY: "sk-6teserrsdf"
    RESPONSE_FORMAT: "json" #"text", "json", "verbose_json"
    LANGUAGE: "af"
    BASE_URL: "http://localhost:8000/v1/"

  ONLINE_LELAPA_VULAVULA:
    MODEL_NAME: "Vulavula"
    LANGUAGE: "afr"

diarizer:
  OFFLINE_PYANNOTE:
    MODEL_NAME: "pyannote/speaker-diarization-3.1"
    DEVICE: "cpu"
    RTTM_PATH: "audio.rttm"



logging:
  version: 1
  disable_existing_loggers: False

  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'

    colored:
      (): configs.configurator.ColoredFormatter
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'

  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: colored
      stream: ext://sys.stdout

    file:
      class: logging.FileHandler
      level: INFO
      formatter: simple
      filename: student_helper_logs.log
      mode: w # a (append logs)

  loggers:
    urllib3:
      level: WARNING
      handlers: [ console ]
      propagate: no

    httpx:
      level: WARNING
      handlers: [ console ]
      propagate: no

    openai:
      level: WARNING
      handlers: [ console ]
      propagate: no

    httpcore:
      level: WARNING
      handlers: [ console ]
      propagate: no


  root:
    level: DEBUG
    handlers: [ console, file ]
